POST HTTP://localhost:3000/login
Content-Type: application/json

{
    "email": "rodrigo@gmail.com",
    "senha": "123456"
}
###

DELETE HTTP://localhost:3000/logout
Authorization: 07b5db3d8eb531237709ac967a39ae8b

###

GET HTTP://localhost:3000/usuarios/1

