POST HTTP://localhost:3000/login
Content-Type: application/json

{
    "email": "rodrigo@gmail.com",
    "senha": "123456"
}
###

DELETE HTTP://localhost:3000/logout
Authorization: 

###

GET HTTP://localhost:3000/usuarios/1
Authorization: 

###
POST HTTP://localhost:3000/usuarios/
Content-Type: application/json
Authorization: 
{
    "nome": "Teste",
    "email": "teste@gmail.com",
    "senha": "123456",
    "idPerfil": 1
}